version: "3"
services:
  mongo:
    image: mongo
    restart: "always"
    volumes:
      - ./.dbcache/mongonew/data:/data/db
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - backend1
  api:
    image: node:10.16-slim
    ports:
      - "3000:3000"
    working_dir: "/home/node/app"
    volumes:
      - ./:/home/node/app
    command: "npm start"
    networks:
      - backend1
  #webxx:
   #  image: "php:7.2-apache"
   #  container_name: php-containerx    
   #  restart: always
   #  volumes:
   #    - ./website:/var/www/html
   #  ports:
   #      - "3050:80"
   #  networks:
   #   - backend1
networks:
  backend1:
    driver: "bridge"